services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "9324:4566"
    environment:
      SERVICES: sqs

  gui:
    image: ghcr.io/shigaichi/sqs-gui:latest
    container_name: gui
    ports:
      - "8080:8080"
    environment:
      AWS_SQS_ENDPOINT: http://localstack:4566
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
