// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package internal

import (
	"context"
	"net/http"

	"github.com/aws/aws-sdk-go-v2/service/sqs"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// DeleteMessageAPI provides a mock function for the type MockHandler
func (_mock *MockHandler) DeleteMessageAPI(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockHandler_DeleteMessageAPI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessageAPI'
type MockHandler_DeleteMessageAPI_Call struct {
	*mock.Call
}

// DeleteMessageAPI is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockHandler_Expecter) DeleteMessageAPI(w interface{}, r interface{}) *MockHandler_DeleteMessageAPI_Call {
	return &MockHandler_DeleteMessageAPI_Call{Call: _e.mock.On("DeleteMessageAPI", w, r)}
}

func (_c *MockHandler_DeleteMessageAPI_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_DeleteMessageAPI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_DeleteMessageAPI_Call) Return() *MockHandler_DeleteMessageAPI_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_DeleteMessageAPI_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_DeleteMessageAPI_Call {
	_c.Run(run)
	return _c
}

// DeleteQueueHandler provides a mock function for the type MockHandler
func (_mock *MockHandler) DeleteQueueHandler(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockHandler_DeleteQueueHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQueueHandler'
type MockHandler_DeleteQueueHandler_Call struct {
	*mock.Call
}

// DeleteQueueHandler is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockHandler_Expecter) DeleteQueueHandler(w interface{}, r interface{}) *MockHandler_DeleteQueueHandler_Call {
	return &MockHandler_DeleteQueueHandler_Call{Call: _e.mock.On("DeleteQueueHandler", w, r)}
}

func (_c *MockHandler_DeleteQueueHandler_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_DeleteQueueHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_DeleteQueueHandler_Call) Return() *MockHandler_DeleteQueueHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_DeleteQueueHandler_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_DeleteQueueHandler_Call {
	_c.Run(run)
	return _c
}

// GetCreateQueueHandler provides a mock function for the type MockHandler
func (_mock *MockHandler) GetCreateQueueHandler(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockHandler_GetCreateQueueHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCreateQueueHandler'
type MockHandler_GetCreateQueueHandler_Call struct {
	*mock.Call
}

// GetCreateQueueHandler is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockHandler_Expecter) GetCreateQueueHandler(w interface{}, r interface{}) *MockHandler_GetCreateQueueHandler_Call {
	return &MockHandler_GetCreateQueueHandler_Call{Call: _e.mock.On("GetCreateQueueHandler", w, r)}
}

func (_c *MockHandler_GetCreateQueueHandler_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_GetCreateQueueHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_GetCreateQueueHandler_Call) Return() *MockHandler_GetCreateQueueHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_GetCreateQueueHandler_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_GetCreateQueueHandler_Call {
	_c.Run(run)
	return _c
}

// PostCreateQueueHandler provides a mock function for the type MockHandler
func (_mock *MockHandler) PostCreateQueueHandler(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockHandler_PostCreateQueueHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostCreateQueueHandler'
type MockHandler_PostCreateQueueHandler_Call struct {
	*mock.Call
}

// PostCreateQueueHandler is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockHandler_Expecter) PostCreateQueueHandler(w interface{}, r interface{}) *MockHandler_PostCreateQueueHandler_Call {
	return &MockHandler_PostCreateQueueHandler_Call{Call: _e.mock.On("PostCreateQueueHandler", w, r)}
}

func (_c *MockHandler_PostCreateQueueHandler_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_PostCreateQueueHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_PostCreateQueueHandler_Call) Return() *MockHandler_PostCreateQueueHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_PostCreateQueueHandler_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_PostCreateQueueHandler_Call {
	_c.Run(run)
	return _c
}

// PurgeQueueHandler provides a mock function for the type MockHandler
func (_mock *MockHandler) PurgeQueueHandler(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockHandler_PurgeQueueHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeQueueHandler'
type MockHandler_PurgeQueueHandler_Call struct {
	*mock.Call
}

// PurgeQueueHandler is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockHandler_Expecter) PurgeQueueHandler(w interface{}, r interface{}) *MockHandler_PurgeQueueHandler_Call {
	return &MockHandler_PurgeQueueHandler_Call{Call: _e.mock.On("PurgeQueueHandler", w, r)}
}

func (_c *MockHandler_PurgeQueueHandler_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_PurgeQueueHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_PurgeQueueHandler_Call) Return() *MockHandler_PurgeQueueHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_PurgeQueueHandler_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_PurgeQueueHandler_Call {
	_c.Run(run)
	return _c
}

// QueueHandler provides a mock function for the type MockHandler
func (_mock *MockHandler) QueueHandler(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockHandler_QueueHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueueHandler'
type MockHandler_QueueHandler_Call struct {
	*mock.Call
}

// QueueHandler is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockHandler_Expecter) QueueHandler(w interface{}, r interface{}) *MockHandler_QueueHandler_Call {
	return &MockHandler_QueueHandler_Call{Call: _e.mock.On("QueueHandler", w, r)}
}

func (_c *MockHandler_QueueHandler_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_QueueHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_QueueHandler_Call) Return() *MockHandler_QueueHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_QueueHandler_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_QueueHandler_Call {
	_c.Run(run)
	return _c
}

// QueuesHandler provides a mock function for the type MockHandler
func (_mock *MockHandler) QueuesHandler(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockHandler_QueuesHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueuesHandler'
type MockHandler_QueuesHandler_Call struct {
	*mock.Call
}

// QueuesHandler is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockHandler_Expecter) QueuesHandler(w interface{}, r interface{}) *MockHandler_QueuesHandler_Call {
	return &MockHandler_QueuesHandler_Call{Call: _e.mock.On("QueuesHandler", w, r)}
}

func (_c *MockHandler_QueuesHandler_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_QueuesHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_QueuesHandler_Call) Return() *MockHandler_QueuesHandler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_QueuesHandler_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_QueuesHandler_Call {
	_c.Run(run)
	return _c
}

// ReceiveMessagesAPI provides a mock function for the type MockHandler
func (_mock *MockHandler) ReceiveMessagesAPI(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockHandler_ReceiveMessagesAPI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReceiveMessagesAPI'
type MockHandler_ReceiveMessagesAPI_Call struct {
	*mock.Call
}

// ReceiveMessagesAPI is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockHandler_Expecter) ReceiveMessagesAPI(w interface{}, r interface{}) *MockHandler_ReceiveMessagesAPI_Call {
	return &MockHandler_ReceiveMessagesAPI_Call{Call: _e.mock.On("ReceiveMessagesAPI", w, r)}
}

func (_c *MockHandler_ReceiveMessagesAPI_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_ReceiveMessagesAPI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_ReceiveMessagesAPI_Call) Return() *MockHandler_ReceiveMessagesAPI_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_ReceiveMessagesAPI_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_ReceiveMessagesAPI_Call {
	_c.Run(run)
	return _c
}

// SendMessageAPI provides a mock function for the type MockHandler
func (_mock *MockHandler) SendMessageAPI(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockHandler_SendMessageAPI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessageAPI'
type MockHandler_SendMessageAPI_Call struct {
	*mock.Call
}

// SendMessageAPI is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockHandler_Expecter) SendMessageAPI(w interface{}, r interface{}) *MockHandler_SendMessageAPI_Call {
	return &MockHandler_SendMessageAPI_Call{Call: _e.mock.On("SendMessageAPI", w, r)}
}

func (_c *MockHandler_SendMessageAPI_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_SendMessageAPI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_SendMessageAPI_Call) Return() *MockHandler_SendMessageAPI_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_SendMessageAPI_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_SendMessageAPI_Call {
	_c.Run(run)
	return _c
}

// SendReceive provides a mock function for the type MockHandler
func (_mock *MockHandler) SendReceive(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockHandler_SendReceive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendReceive'
type MockHandler_SendReceive_Call struct {
	*mock.Call
}

// SendReceive is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockHandler_Expecter) SendReceive(w interface{}, r interface{}) *MockHandler_SendReceive_Call {
	return &MockHandler_SendReceive_Call{Call: _e.mock.On("SendReceive", w, r)}
}

func (_c *MockHandler_SendReceive_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_SendReceive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_SendReceive_Call) Return() *MockHandler_SendReceive_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_SendReceive_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockHandler_SendReceive_Call {
	_c.Run(run)
	return _c
}

// NewMockRoute creates a new instance of MockRoute. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoute(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoute {
	mock := &MockRoute{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoute is an autogenerated mock type for the Route type
type MockRoute struct {
	mock.Mock
}

type MockRoute_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoute) EXPECT() *MockRoute_Expecter {
	return &MockRoute_Expecter{mock: &_m.Mock}
}

// InitRoute provides a mock function for the type MockRoute
func (_mock *MockRoute) InitRoute() (http.Handler, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for InitRoute")
	}

	var r0 http.Handler
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (http.Handler, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() http.Handler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoute_InitRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitRoute'
type MockRoute_InitRoute_Call struct {
	*mock.Call
}

// InitRoute is a helper method to define mock.On call
func (_e *MockRoute_Expecter) InitRoute() *MockRoute_InitRoute_Call {
	return &MockRoute_InitRoute_Call{Call: _e.mock.On("InitRoute")}
}

func (_c *MockRoute_InitRoute_Call) Run(run func()) *MockRoute_InitRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRoute_InitRoute_Call) Return(handler http.Handler, err error) *MockRoute_InitRoute_Call {
	_c.Call.Return(handler, err)
	return _c
}

func (_c *MockRoute_InitRoute_Call) RunAndReturn(run func() (http.Handler, error)) *MockRoute_InitRoute_Call {
	_c.Call.Return(run)
	return _c
}

// newMocksqsAPI creates a new instance of mocksqsAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocksqsAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocksqsAPI {
	mock := &mocksqsAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocksqsAPI is an autogenerated mock type for the sqsAPI type
type mocksqsAPI struct {
	mock.Mock
}

type mocksqsAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *mocksqsAPI) EXPECT() *mocksqsAPI_Expecter {
	return &mocksqsAPI_Expecter{mock: &_m.Mock}
}

// CreateQueue provides a mock function for the type mocksqsAPI
func (_mock *mocksqsAPI) CreateQueue(ctx context.Context, params *sqs.CreateQueueInput, optFns ...func(*sqs.Options)) (*sqs.CreateQueueOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateQueue")
	}

	var r0 *sqs.CreateQueueOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.CreateQueueInput, ...func(*sqs.Options)) (*sqs.CreateQueueOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.CreateQueueInput, ...func(*sqs.Options)) *sqs.CreateQueueOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.CreateQueueOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.CreateQueueInput, ...func(*sqs.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksqsAPI_CreateQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateQueue'
type mocksqsAPI_CreateQueue_Call struct {
	*mock.Call
}

// CreateQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sqs.CreateQueueInput
//   - optFns ...func(*sqs.Options)
func (_e *mocksqsAPI_Expecter) CreateQueue(ctx interface{}, params interface{}, optFns ...interface{}) *mocksqsAPI_CreateQueue_Call {
	return &mocksqsAPI_CreateQueue_Call{Call: _e.mock.On("CreateQueue",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *mocksqsAPI_CreateQueue_Call) Run(run func(ctx context.Context, params *sqs.CreateQueueInput, optFns ...func(*sqs.Options))) *mocksqsAPI_CreateQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.CreateQueueInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.CreateQueueInput)
		}
		var arg2 []func(*sqs.Options)
		var variadicArgs []func(*sqs.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*sqs.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocksqsAPI_CreateQueue_Call) Return(createQueueOutput *sqs.CreateQueueOutput, err error) *mocksqsAPI_CreateQueue_Call {
	_c.Call.Return(createQueueOutput, err)
	return _c
}

func (_c *mocksqsAPI_CreateQueue_Call) RunAndReturn(run func(ctx context.Context, params *sqs.CreateQueueInput, optFns ...func(*sqs.Options)) (*sqs.CreateQueueOutput, error)) *mocksqsAPI_CreateQueue_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMessage provides a mock function for the type mocksqsAPI
func (_mock *mocksqsAPI) DeleteMessage(ctx context.Context, params *sqs.DeleteMessageInput, optFns ...func(*sqs.Options)) (*sqs.DeleteMessageOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 *sqs.DeleteMessageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.DeleteMessageInput, ...func(*sqs.Options)) (*sqs.DeleteMessageOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.DeleteMessageInput, ...func(*sqs.Options)) *sqs.DeleteMessageOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.DeleteMessageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.DeleteMessageInput, ...func(*sqs.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksqsAPI_DeleteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessage'
type mocksqsAPI_DeleteMessage_Call struct {
	*mock.Call
}

// DeleteMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sqs.DeleteMessageInput
//   - optFns ...func(*sqs.Options)
func (_e *mocksqsAPI_Expecter) DeleteMessage(ctx interface{}, params interface{}, optFns ...interface{}) *mocksqsAPI_DeleteMessage_Call {
	return &mocksqsAPI_DeleteMessage_Call{Call: _e.mock.On("DeleteMessage",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *mocksqsAPI_DeleteMessage_Call) Run(run func(ctx context.Context, params *sqs.DeleteMessageInput, optFns ...func(*sqs.Options))) *mocksqsAPI_DeleteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.DeleteMessageInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.DeleteMessageInput)
		}
		var arg2 []func(*sqs.Options)
		var variadicArgs []func(*sqs.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*sqs.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocksqsAPI_DeleteMessage_Call) Return(deleteMessageOutput *sqs.DeleteMessageOutput, err error) *mocksqsAPI_DeleteMessage_Call {
	_c.Call.Return(deleteMessageOutput, err)
	return _c
}

func (_c *mocksqsAPI_DeleteMessage_Call) RunAndReturn(run func(ctx context.Context, params *sqs.DeleteMessageInput, optFns ...func(*sqs.Options)) (*sqs.DeleteMessageOutput, error)) *mocksqsAPI_DeleteMessage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteQueue provides a mock function for the type mocksqsAPI
func (_mock *mocksqsAPI) DeleteQueue(ctx context.Context, params *sqs.DeleteQueueInput, optFns ...func(*sqs.Options)) (*sqs.DeleteQueueOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteQueue")
	}

	var r0 *sqs.DeleteQueueOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.DeleteQueueInput, ...func(*sqs.Options)) (*sqs.DeleteQueueOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.DeleteQueueInput, ...func(*sqs.Options)) *sqs.DeleteQueueOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.DeleteQueueOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.DeleteQueueInput, ...func(*sqs.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksqsAPI_DeleteQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQueue'
type mocksqsAPI_DeleteQueue_Call struct {
	*mock.Call
}

// DeleteQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sqs.DeleteQueueInput
//   - optFns ...func(*sqs.Options)
func (_e *mocksqsAPI_Expecter) DeleteQueue(ctx interface{}, params interface{}, optFns ...interface{}) *mocksqsAPI_DeleteQueue_Call {
	return &mocksqsAPI_DeleteQueue_Call{Call: _e.mock.On("DeleteQueue",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *mocksqsAPI_DeleteQueue_Call) Run(run func(ctx context.Context, params *sqs.DeleteQueueInput, optFns ...func(*sqs.Options))) *mocksqsAPI_DeleteQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.DeleteQueueInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.DeleteQueueInput)
		}
		var arg2 []func(*sqs.Options)
		var variadicArgs []func(*sqs.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*sqs.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocksqsAPI_DeleteQueue_Call) Return(deleteQueueOutput *sqs.DeleteQueueOutput, err error) *mocksqsAPI_DeleteQueue_Call {
	_c.Call.Return(deleteQueueOutput, err)
	return _c
}

func (_c *mocksqsAPI_DeleteQueue_Call) RunAndReturn(run func(ctx context.Context, params *sqs.DeleteQueueInput, optFns ...func(*sqs.Options)) (*sqs.DeleteQueueOutput, error)) *mocksqsAPI_DeleteQueue_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueueAttributes provides a mock function for the type mocksqsAPI
func (_mock *mocksqsAPI) GetQueueAttributes(ctx context.Context, params *sqs.GetQueueAttributesInput, optFns ...func(*sqs.Options)) (*sqs.GetQueueAttributesOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetQueueAttributes")
	}

	var r0 *sqs.GetQueueAttributesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.GetQueueAttributesInput, ...func(*sqs.Options)) (*sqs.GetQueueAttributesOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.GetQueueAttributesInput, ...func(*sqs.Options)) *sqs.GetQueueAttributesOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.GetQueueAttributesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.GetQueueAttributesInput, ...func(*sqs.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksqsAPI_GetQueueAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueueAttributes'
type mocksqsAPI_GetQueueAttributes_Call struct {
	*mock.Call
}

// GetQueueAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sqs.GetQueueAttributesInput
//   - optFns ...func(*sqs.Options)
func (_e *mocksqsAPI_Expecter) GetQueueAttributes(ctx interface{}, params interface{}, optFns ...interface{}) *mocksqsAPI_GetQueueAttributes_Call {
	return &mocksqsAPI_GetQueueAttributes_Call{Call: _e.mock.On("GetQueueAttributes",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *mocksqsAPI_GetQueueAttributes_Call) Run(run func(ctx context.Context, params *sqs.GetQueueAttributesInput, optFns ...func(*sqs.Options))) *mocksqsAPI_GetQueueAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.GetQueueAttributesInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.GetQueueAttributesInput)
		}
		var arg2 []func(*sqs.Options)
		var variadicArgs []func(*sqs.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*sqs.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocksqsAPI_GetQueueAttributes_Call) Return(getQueueAttributesOutput *sqs.GetQueueAttributesOutput, err error) *mocksqsAPI_GetQueueAttributes_Call {
	_c.Call.Return(getQueueAttributesOutput, err)
	return _c
}

func (_c *mocksqsAPI_GetQueueAttributes_Call) RunAndReturn(run func(ctx context.Context, params *sqs.GetQueueAttributesInput, optFns ...func(*sqs.Options)) (*sqs.GetQueueAttributesOutput, error)) *mocksqsAPI_GetQueueAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// ListQueueTags provides a mock function for the type mocksqsAPI
func (_mock *mocksqsAPI) ListQueueTags(ctx context.Context, params *sqs.ListQueueTagsInput, optFns ...func(*sqs.Options)) (*sqs.ListQueueTagsOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListQueueTags")
	}

	var r0 *sqs.ListQueueTagsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.ListQueueTagsInput, ...func(*sqs.Options)) (*sqs.ListQueueTagsOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.ListQueueTagsInput, ...func(*sqs.Options)) *sqs.ListQueueTagsOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.ListQueueTagsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.ListQueueTagsInput, ...func(*sqs.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksqsAPI_ListQueueTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListQueueTags'
type mocksqsAPI_ListQueueTags_Call struct {
	*mock.Call
}

// ListQueueTags is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sqs.ListQueueTagsInput
//   - optFns ...func(*sqs.Options)
func (_e *mocksqsAPI_Expecter) ListQueueTags(ctx interface{}, params interface{}, optFns ...interface{}) *mocksqsAPI_ListQueueTags_Call {
	return &mocksqsAPI_ListQueueTags_Call{Call: _e.mock.On("ListQueueTags",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *mocksqsAPI_ListQueueTags_Call) Run(run func(ctx context.Context, params *sqs.ListQueueTagsInput, optFns ...func(*sqs.Options))) *mocksqsAPI_ListQueueTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.ListQueueTagsInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.ListQueueTagsInput)
		}
		var arg2 []func(*sqs.Options)
		var variadicArgs []func(*sqs.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*sqs.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocksqsAPI_ListQueueTags_Call) Return(listQueueTagsOutput *sqs.ListQueueTagsOutput, err error) *mocksqsAPI_ListQueueTags_Call {
	_c.Call.Return(listQueueTagsOutput, err)
	return _c
}

func (_c *mocksqsAPI_ListQueueTags_Call) RunAndReturn(run func(ctx context.Context, params *sqs.ListQueueTagsInput, optFns ...func(*sqs.Options)) (*sqs.ListQueueTagsOutput, error)) *mocksqsAPI_ListQueueTags_Call {
	_c.Call.Return(run)
	return _c
}

// ListQueues provides a mock function for the type mocksqsAPI
func (_mock *mocksqsAPI) ListQueues(ctx context.Context, params *sqs.ListQueuesInput, optFns ...func(*sqs.Options)) (*sqs.ListQueuesOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListQueues")
	}

	var r0 *sqs.ListQueuesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.ListQueuesInput, ...func(*sqs.Options)) (*sqs.ListQueuesOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.ListQueuesInput, ...func(*sqs.Options)) *sqs.ListQueuesOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.ListQueuesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.ListQueuesInput, ...func(*sqs.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksqsAPI_ListQueues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListQueues'
type mocksqsAPI_ListQueues_Call struct {
	*mock.Call
}

// ListQueues is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sqs.ListQueuesInput
//   - optFns ...func(*sqs.Options)
func (_e *mocksqsAPI_Expecter) ListQueues(ctx interface{}, params interface{}, optFns ...interface{}) *mocksqsAPI_ListQueues_Call {
	return &mocksqsAPI_ListQueues_Call{Call: _e.mock.On("ListQueues",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *mocksqsAPI_ListQueues_Call) Run(run func(ctx context.Context, params *sqs.ListQueuesInput, optFns ...func(*sqs.Options))) *mocksqsAPI_ListQueues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.ListQueuesInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.ListQueuesInput)
		}
		var arg2 []func(*sqs.Options)
		var variadicArgs []func(*sqs.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*sqs.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocksqsAPI_ListQueues_Call) Return(listQueuesOutput *sqs.ListQueuesOutput, err error) *mocksqsAPI_ListQueues_Call {
	_c.Call.Return(listQueuesOutput, err)
	return _c
}

func (_c *mocksqsAPI_ListQueues_Call) RunAndReturn(run func(ctx context.Context, params *sqs.ListQueuesInput, optFns ...func(*sqs.Options)) (*sqs.ListQueuesOutput, error)) *mocksqsAPI_ListQueues_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeQueue provides a mock function for the type mocksqsAPI
func (_mock *mocksqsAPI) PurgeQueue(ctx context.Context, params *sqs.PurgeQueueInput, optFns ...func(*sqs.Options)) (*sqs.PurgeQueueOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PurgeQueue")
	}

	var r0 *sqs.PurgeQueueOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.PurgeQueueInput, ...func(*sqs.Options)) (*sqs.PurgeQueueOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.PurgeQueueInput, ...func(*sqs.Options)) *sqs.PurgeQueueOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.PurgeQueueOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.PurgeQueueInput, ...func(*sqs.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksqsAPI_PurgeQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeQueue'
type mocksqsAPI_PurgeQueue_Call struct {
	*mock.Call
}

// PurgeQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sqs.PurgeQueueInput
//   - optFns ...func(*sqs.Options)
func (_e *mocksqsAPI_Expecter) PurgeQueue(ctx interface{}, params interface{}, optFns ...interface{}) *mocksqsAPI_PurgeQueue_Call {
	return &mocksqsAPI_PurgeQueue_Call{Call: _e.mock.On("PurgeQueue",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *mocksqsAPI_PurgeQueue_Call) Run(run func(ctx context.Context, params *sqs.PurgeQueueInput, optFns ...func(*sqs.Options))) *mocksqsAPI_PurgeQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.PurgeQueueInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.PurgeQueueInput)
		}
		var arg2 []func(*sqs.Options)
		var variadicArgs []func(*sqs.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*sqs.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocksqsAPI_PurgeQueue_Call) Return(purgeQueueOutput *sqs.PurgeQueueOutput, err error) *mocksqsAPI_PurgeQueue_Call {
	_c.Call.Return(purgeQueueOutput, err)
	return _c
}

func (_c *mocksqsAPI_PurgeQueue_Call) RunAndReturn(run func(ctx context.Context, params *sqs.PurgeQueueInput, optFns ...func(*sqs.Options)) (*sqs.PurgeQueueOutput, error)) *mocksqsAPI_PurgeQueue_Call {
	_c.Call.Return(run)
	return _c
}

// ReceiveMessage provides a mock function for the type mocksqsAPI
func (_mock *mocksqsAPI) ReceiveMessage(ctx context.Context, params *sqs.ReceiveMessageInput, optFns ...func(*sqs.Options)) (*sqs.ReceiveMessageOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ReceiveMessage")
	}

	var r0 *sqs.ReceiveMessageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.ReceiveMessageInput, ...func(*sqs.Options)) (*sqs.ReceiveMessageOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.ReceiveMessageInput, ...func(*sqs.Options)) *sqs.ReceiveMessageOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.ReceiveMessageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.ReceiveMessageInput, ...func(*sqs.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksqsAPI_ReceiveMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReceiveMessage'
type mocksqsAPI_ReceiveMessage_Call struct {
	*mock.Call
}

// ReceiveMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sqs.ReceiveMessageInput
//   - optFns ...func(*sqs.Options)
func (_e *mocksqsAPI_Expecter) ReceiveMessage(ctx interface{}, params interface{}, optFns ...interface{}) *mocksqsAPI_ReceiveMessage_Call {
	return &mocksqsAPI_ReceiveMessage_Call{Call: _e.mock.On("ReceiveMessage",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *mocksqsAPI_ReceiveMessage_Call) Run(run func(ctx context.Context, params *sqs.ReceiveMessageInput, optFns ...func(*sqs.Options))) *mocksqsAPI_ReceiveMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.ReceiveMessageInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.ReceiveMessageInput)
		}
		var arg2 []func(*sqs.Options)
		var variadicArgs []func(*sqs.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*sqs.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocksqsAPI_ReceiveMessage_Call) Return(receiveMessageOutput *sqs.ReceiveMessageOutput, err error) *mocksqsAPI_ReceiveMessage_Call {
	_c.Call.Return(receiveMessageOutput, err)
	return _c
}

func (_c *mocksqsAPI_ReceiveMessage_Call) RunAndReturn(run func(ctx context.Context, params *sqs.ReceiveMessageInput, optFns ...func(*sqs.Options)) (*sqs.ReceiveMessageOutput, error)) *mocksqsAPI_ReceiveMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type mocksqsAPI
func (_mock *mocksqsAPI) SendMessage(ctx context.Context, params *sqs.SendMessageInput, optFns ...func(*sqs.Options)) (*sqs.SendMessageOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *sqs.SendMessageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.SendMessageInput, ...func(*sqs.Options)) (*sqs.SendMessageOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.SendMessageInput, ...func(*sqs.Options)) *sqs.SendMessageOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.SendMessageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.SendMessageInput, ...func(*sqs.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksqsAPI_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type mocksqsAPI_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sqs.SendMessageInput
//   - optFns ...func(*sqs.Options)
func (_e *mocksqsAPI_Expecter) SendMessage(ctx interface{}, params interface{}, optFns ...interface{}) *mocksqsAPI_SendMessage_Call {
	return &mocksqsAPI_SendMessage_Call{Call: _e.mock.On("SendMessage",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *mocksqsAPI_SendMessage_Call) Run(run func(ctx context.Context, params *sqs.SendMessageInput, optFns ...func(*sqs.Options))) *mocksqsAPI_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.SendMessageInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.SendMessageInput)
		}
		var arg2 []func(*sqs.Options)
		var variadicArgs []func(*sqs.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*sqs.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *mocksqsAPI_SendMessage_Call) Return(sendMessageOutput *sqs.SendMessageOutput, err error) *mocksqsAPI_SendMessage_Call {
	_c.Call.Return(sendMessageOutput, err)
	return _c
}

func (_c *mocksqsAPI_SendMessage_Call) RunAndReturn(run func(ctx context.Context, params *sqs.SendMessageInput, optFns ...func(*sqs.Options)) (*sqs.SendMessageOutput, error)) *mocksqsAPI_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSqsRepository creates a new instance of MockSqsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSqsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSqsRepository {
	mock := &MockSqsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSqsRepository is an autogenerated mock type for the SqsRepository type
type MockSqsRepository struct {
	mock.Mock
}

type MockSqsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSqsRepository) EXPECT() *MockSqsRepository_Expecter {
	return &MockSqsRepository_Expecter{mock: &_m.Mock}
}

// CreateQueue provides a mock function for the type MockSqsRepository
func (_mock *MockSqsRepository) CreateQueue(ctx context.Context, input CreateQueueRepositoryInput) (string, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateQueue")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateQueueRepositoryInput) (string, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateQueueRepositoryInput) string); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateQueueRepositoryInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSqsRepository_CreateQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateQueue'
type MockSqsRepository_CreateQueue_Call struct {
	*mock.Call
}

// CreateQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - input CreateQueueRepositoryInput
func (_e *MockSqsRepository_Expecter) CreateQueue(ctx interface{}, input interface{}) *MockSqsRepository_CreateQueue_Call {
	return &MockSqsRepository_CreateQueue_Call{Call: _e.mock.On("CreateQueue", ctx, input)}
}

func (_c *MockSqsRepository_CreateQueue_Call) Run(run func(ctx context.Context, input CreateQueueRepositoryInput)) *MockSqsRepository_CreateQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateQueueRepositoryInput
		if args[1] != nil {
			arg1 = args[1].(CreateQueueRepositoryInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSqsRepository_CreateQueue_Call) Return(s string, err error) *MockSqsRepository_CreateQueue_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSqsRepository_CreateQueue_Call) RunAndReturn(run func(ctx context.Context, input CreateQueueRepositoryInput) (string, error)) *MockSqsRepository_CreateQueue_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMessage provides a mock function for the type MockSqsRepository
func (_mock *MockSqsRepository) DeleteMessage(ctx context.Context, input DeleteMessageRepositoryInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, DeleteMessageRepositoryInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSqsRepository_DeleteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessage'
type MockSqsRepository_DeleteMessage_Call struct {
	*mock.Call
}

// DeleteMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - input DeleteMessageRepositoryInput
func (_e *MockSqsRepository_Expecter) DeleteMessage(ctx interface{}, input interface{}) *MockSqsRepository_DeleteMessage_Call {
	return &MockSqsRepository_DeleteMessage_Call{Call: _e.mock.On("DeleteMessage", ctx, input)}
}

func (_c *MockSqsRepository_DeleteMessage_Call) Run(run func(ctx context.Context, input DeleteMessageRepositoryInput)) *MockSqsRepository_DeleteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 DeleteMessageRepositoryInput
		if args[1] != nil {
			arg1 = args[1].(DeleteMessageRepositoryInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSqsRepository_DeleteMessage_Call) Return(err error) *MockSqsRepository_DeleteMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSqsRepository_DeleteMessage_Call) RunAndReturn(run func(ctx context.Context, input DeleteMessageRepositoryInput) error) *MockSqsRepository_DeleteMessage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteQueue provides a mock function for the type MockSqsRepository
func (_mock *MockSqsRepository) DeleteQueue(ctx context.Context, queueURL string) error {
	ret := _mock.Called(ctx, queueURL)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQueue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, queueURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSqsRepository_DeleteQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQueue'
type MockSqsRepository_DeleteQueue_Call struct {
	*mock.Call
}

// DeleteQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - queueURL string
func (_e *MockSqsRepository_Expecter) DeleteQueue(ctx interface{}, queueURL interface{}) *MockSqsRepository_DeleteQueue_Call {
	return &MockSqsRepository_DeleteQueue_Call{Call: _e.mock.On("DeleteQueue", ctx, queueURL)}
}

func (_c *MockSqsRepository_DeleteQueue_Call) Run(run func(ctx context.Context, queueURL string)) *MockSqsRepository_DeleteQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSqsRepository_DeleteQueue_Call) Return(err error) *MockSqsRepository_DeleteQueue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSqsRepository_DeleteQueue_Call) RunAndReturn(run func(ctx context.Context, queueURL string) error) *MockSqsRepository_DeleteQueue_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueueDetail provides a mock function for the type MockSqsRepository
func (_mock *MockSqsRepository) GetQueueDetail(ctx context.Context, queueURL string) (QueueDetail, error) {
	ret := _mock.Called(ctx, queueURL)

	if len(ret) == 0 {
		panic("no return value specified for GetQueueDetail")
	}

	var r0 QueueDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (QueueDetail, error)); ok {
		return returnFunc(ctx, queueURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) QueueDetail); ok {
		r0 = returnFunc(ctx, queueURL)
	} else {
		r0 = ret.Get(0).(QueueDetail)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, queueURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSqsRepository_GetQueueDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueueDetail'
type MockSqsRepository_GetQueueDetail_Call struct {
	*mock.Call
}

// GetQueueDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - queueURL string
func (_e *MockSqsRepository_Expecter) GetQueueDetail(ctx interface{}, queueURL interface{}) *MockSqsRepository_GetQueueDetail_Call {
	return &MockSqsRepository_GetQueueDetail_Call{Call: _e.mock.On("GetQueueDetail", ctx, queueURL)}
}

func (_c *MockSqsRepository_GetQueueDetail_Call) Run(run func(ctx context.Context, queueURL string)) *MockSqsRepository_GetQueueDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSqsRepository_GetQueueDetail_Call) Return(queueDetail QueueDetail, err error) *MockSqsRepository_GetQueueDetail_Call {
	_c.Call.Return(queueDetail, err)
	return _c
}

func (_c *MockSqsRepository_GetQueueDetail_Call) RunAndReturn(run func(ctx context.Context, queueURL string) (QueueDetail, error)) *MockSqsRepository_GetQueueDetail_Call {
	_c.Call.Return(run)
	return _c
}

// ListQueues provides a mock function for the type MockSqsRepository
func (_mock *MockSqsRepository) ListQueues(ctx context.Context) ([]QueueSummary, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListQueues")
	}

	var r0 []QueueSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]QueueSummary, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []QueueSummary); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]QueueSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSqsRepository_ListQueues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListQueues'
type MockSqsRepository_ListQueues_Call struct {
	*mock.Call
}

// ListQueues is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSqsRepository_Expecter) ListQueues(ctx interface{}) *MockSqsRepository_ListQueues_Call {
	return &MockSqsRepository_ListQueues_Call{Call: _e.mock.On("ListQueues", ctx)}
}

func (_c *MockSqsRepository_ListQueues_Call) Run(run func(ctx context.Context)) *MockSqsRepository_ListQueues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSqsRepository_ListQueues_Call) Return(queueSummarys []QueueSummary, err error) *MockSqsRepository_ListQueues_Call {
	_c.Call.Return(queueSummarys, err)
	return _c
}

func (_c *MockSqsRepository_ListQueues_Call) RunAndReturn(run func(ctx context.Context) ([]QueueSummary, error)) *MockSqsRepository_ListQueues_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeQueue provides a mock function for the type MockSqsRepository
func (_mock *MockSqsRepository) PurgeQueue(ctx context.Context, queueURL string) error {
	ret := _mock.Called(ctx, queueURL)

	if len(ret) == 0 {
		panic("no return value specified for PurgeQueue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, queueURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSqsRepository_PurgeQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeQueue'
type MockSqsRepository_PurgeQueue_Call struct {
	*mock.Call
}

// PurgeQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - queueURL string
func (_e *MockSqsRepository_Expecter) PurgeQueue(ctx interface{}, queueURL interface{}) *MockSqsRepository_PurgeQueue_Call {
	return &MockSqsRepository_PurgeQueue_Call{Call: _e.mock.On("PurgeQueue", ctx, queueURL)}
}

func (_c *MockSqsRepository_PurgeQueue_Call) Run(run func(ctx context.Context, queueURL string)) *MockSqsRepository_PurgeQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSqsRepository_PurgeQueue_Call) Return(err error) *MockSqsRepository_PurgeQueue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSqsRepository_PurgeQueue_Call) RunAndReturn(run func(ctx context.Context, queueURL string) error) *MockSqsRepository_PurgeQueue_Call {
	_c.Call.Return(run)
	return _c
}

// ReceiveMessages provides a mock function for the type MockSqsRepository
func (_mock *MockSqsRepository) ReceiveMessages(ctx context.Context, input ReceiveMessagesRepositoryInput) ([]ReceivedMessage, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ReceiveMessages")
	}

	var r0 []ReceivedMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ReceiveMessagesRepositoryInput) ([]ReceivedMessage, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ReceiveMessagesRepositoryInput) []ReceivedMessage); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ReceivedMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ReceiveMessagesRepositoryInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSqsRepository_ReceiveMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReceiveMessages'
type MockSqsRepository_ReceiveMessages_Call struct {
	*mock.Call
}

// ReceiveMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - input ReceiveMessagesRepositoryInput
func (_e *MockSqsRepository_Expecter) ReceiveMessages(ctx interface{}, input interface{}) *MockSqsRepository_ReceiveMessages_Call {
	return &MockSqsRepository_ReceiveMessages_Call{Call: _e.mock.On("ReceiveMessages", ctx, input)}
}

func (_c *MockSqsRepository_ReceiveMessages_Call) Run(run func(ctx context.Context, input ReceiveMessagesRepositoryInput)) *MockSqsRepository_ReceiveMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ReceiveMessagesRepositoryInput
		if args[1] != nil {
			arg1 = args[1].(ReceiveMessagesRepositoryInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSqsRepository_ReceiveMessages_Call) Return(receivedMessages []ReceivedMessage, err error) *MockSqsRepository_ReceiveMessages_Call {
	_c.Call.Return(receivedMessages, err)
	return _c
}

func (_c *MockSqsRepository_ReceiveMessages_Call) RunAndReturn(run func(ctx context.Context, input ReceiveMessagesRepositoryInput) ([]ReceivedMessage, error)) *MockSqsRepository_ReceiveMessages_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type MockSqsRepository
func (_mock *MockSqsRepository) SendMessage(ctx context.Context, input SendMessageRepositoryInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, SendMessageRepositoryInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSqsRepository_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockSqsRepository_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - input SendMessageRepositoryInput
func (_e *MockSqsRepository_Expecter) SendMessage(ctx interface{}, input interface{}) *MockSqsRepository_SendMessage_Call {
	return &MockSqsRepository_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, input)}
}

func (_c *MockSqsRepository_SendMessage_Call) Run(run func(ctx context.Context, input SendMessageRepositoryInput)) *MockSqsRepository_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 SendMessageRepositoryInput
		if args[1] != nil {
			arg1 = args[1].(SendMessageRepositoryInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSqsRepository_SendMessage_Call) Return(err error) *MockSqsRepository_SendMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSqsRepository_SendMessage_Call) RunAndReturn(run func(ctx context.Context, input SendMessageRepositoryInput) error) *MockSqsRepository_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSqsService creates a new instance of MockSqsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSqsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSqsService {
	mock := &MockSqsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSqsService is an autogenerated mock type for the SqsService type
type MockSqsService struct {
	mock.Mock
}

type MockSqsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSqsService) EXPECT() *MockSqsService_Expecter {
	return &MockSqsService_Expecter{mock: &_m.Mock}
}

// CreateQueue provides a mock function for the type MockSqsService
func (_mock *MockSqsService) CreateQueue(ctx context.Context, input CreateQueueInput) (CreateQueueResult, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateQueue")
	}

	var r0 CreateQueueResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateQueueInput) (CreateQueueResult, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateQueueInput) CreateQueueResult); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(CreateQueueResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateQueueInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSqsService_CreateQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateQueue'
type MockSqsService_CreateQueue_Call struct {
	*mock.Call
}

// CreateQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - input CreateQueueInput
func (_e *MockSqsService_Expecter) CreateQueue(ctx interface{}, input interface{}) *MockSqsService_CreateQueue_Call {
	return &MockSqsService_CreateQueue_Call{Call: _e.mock.On("CreateQueue", ctx, input)}
}

func (_c *MockSqsService_CreateQueue_Call) Run(run func(ctx context.Context, input CreateQueueInput)) *MockSqsService_CreateQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateQueueInput
		if args[1] != nil {
			arg1 = args[1].(CreateQueueInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSqsService_CreateQueue_Call) Return(createQueueResult CreateQueueResult, err error) *MockSqsService_CreateQueue_Call {
	_c.Call.Return(createQueueResult, err)
	return _c
}

func (_c *MockSqsService_CreateQueue_Call) RunAndReturn(run func(ctx context.Context, input CreateQueueInput) (CreateQueueResult, error)) *MockSqsService_CreateQueue_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMessage provides a mock function for the type MockSqsService
func (_mock *MockSqsService) DeleteMessage(ctx context.Context, input DeleteMessageInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, DeleteMessageInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSqsService_DeleteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessage'
type MockSqsService_DeleteMessage_Call struct {
	*mock.Call
}

// DeleteMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - input DeleteMessageInput
func (_e *MockSqsService_Expecter) DeleteMessage(ctx interface{}, input interface{}) *MockSqsService_DeleteMessage_Call {
	return &MockSqsService_DeleteMessage_Call{Call: _e.mock.On("DeleteMessage", ctx, input)}
}

func (_c *MockSqsService_DeleteMessage_Call) Run(run func(ctx context.Context, input DeleteMessageInput)) *MockSqsService_DeleteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 DeleteMessageInput
		if args[1] != nil {
			arg1 = args[1].(DeleteMessageInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSqsService_DeleteMessage_Call) Return(err error) *MockSqsService_DeleteMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSqsService_DeleteMessage_Call) RunAndReturn(run func(ctx context.Context, input DeleteMessageInput) error) *MockSqsService_DeleteMessage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteQueue provides a mock function for the type MockSqsService
func (_mock *MockSqsService) DeleteQueue(ctx context.Context, queueURL string) error {
	ret := _mock.Called(ctx, queueURL)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQueue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, queueURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSqsService_DeleteQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQueue'
type MockSqsService_DeleteQueue_Call struct {
	*mock.Call
}

// DeleteQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - queueURL string
func (_e *MockSqsService_Expecter) DeleteQueue(ctx interface{}, queueURL interface{}) *MockSqsService_DeleteQueue_Call {
	return &MockSqsService_DeleteQueue_Call{Call: _e.mock.On("DeleteQueue", ctx, queueURL)}
}

func (_c *MockSqsService_DeleteQueue_Call) Run(run func(ctx context.Context, queueURL string)) *MockSqsService_DeleteQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSqsService_DeleteQueue_Call) Return(err error) *MockSqsService_DeleteQueue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSqsService_DeleteQueue_Call) RunAndReturn(run func(ctx context.Context, queueURL string) error) *MockSqsService_DeleteQueue_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeQueue provides a mock function for the type MockSqsService
func (_mock *MockSqsService) PurgeQueue(ctx context.Context, queueURL string) error {
	ret := _mock.Called(ctx, queueURL)

	if len(ret) == 0 {
		panic("no return value specified for PurgeQueue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, queueURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSqsService_PurgeQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeQueue'
type MockSqsService_PurgeQueue_Call struct {
	*mock.Call
}

// PurgeQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - queueURL string
func (_e *MockSqsService_Expecter) PurgeQueue(ctx interface{}, queueURL interface{}) *MockSqsService_PurgeQueue_Call {
	return &MockSqsService_PurgeQueue_Call{Call: _e.mock.On("PurgeQueue", ctx, queueURL)}
}

func (_c *MockSqsService_PurgeQueue_Call) Run(run func(ctx context.Context, queueURL string)) *MockSqsService_PurgeQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSqsService_PurgeQueue_Call) Return(err error) *MockSqsService_PurgeQueue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSqsService_PurgeQueue_Call) RunAndReturn(run func(ctx context.Context, queueURL string) error) *MockSqsService_PurgeQueue_Call {
	_c.Call.Return(run)
	return _c
}

// QueueDetail provides a mock function for the type MockSqsService
func (_mock *MockSqsService) QueueDetail(ctx context.Context, queueURL string) (QueueDetail, error) {
	ret := _mock.Called(ctx, queueURL)

	if len(ret) == 0 {
		panic("no return value specified for QueueDetail")
	}

	var r0 QueueDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (QueueDetail, error)); ok {
		return returnFunc(ctx, queueURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) QueueDetail); ok {
		r0 = returnFunc(ctx, queueURL)
	} else {
		r0 = ret.Get(0).(QueueDetail)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, queueURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSqsService_QueueDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueueDetail'
type MockSqsService_QueueDetail_Call struct {
	*mock.Call
}

// QueueDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - queueURL string
func (_e *MockSqsService_Expecter) QueueDetail(ctx interface{}, queueURL interface{}) *MockSqsService_QueueDetail_Call {
	return &MockSqsService_QueueDetail_Call{Call: _e.mock.On("QueueDetail", ctx, queueURL)}
}

func (_c *MockSqsService_QueueDetail_Call) Run(run func(ctx context.Context, queueURL string)) *MockSqsService_QueueDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSqsService_QueueDetail_Call) Return(queueDetail QueueDetail, err error) *MockSqsService_QueueDetail_Call {
	_c.Call.Return(queueDetail, err)
	return _c
}

func (_c *MockSqsService_QueueDetail_Call) RunAndReturn(run func(ctx context.Context, queueURL string) (QueueDetail, error)) *MockSqsService_QueueDetail_Call {
	_c.Call.Return(run)
	return _c
}

// Queues provides a mock function for the type MockSqsService
func (_mock *MockSqsService) Queues(ctx context.Context) ([]QueueSummary, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Queues")
	}

	var r0 []QueueSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]QueueSummary, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []QueueSummary); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]QueueSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSqsService_Queues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Queues'
type MockSqsService_Queues_Call struct {
	*mock.Call
}

// Queues is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSqsService_Expecter) Queues(ctx interface{}) *MockSqsService_Queues_Call {
	return &MockSqsService_Queues_Call{Call: _e.mock.On("Queues", ctx)}
}

func (_c *MockSqsService_Queues_Call) Run(run func(ctx context.Context)) *MockSqsService_Queues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSqsService_Queues_Call) Return(queueSummarys []QueueSummary, err error) *MockSqsService_Queues_Call {
	_c.Call.Return(queueSummarys, err)
	return _c
}

func (_c *MockSqsService_Queues_Call) RunAndReturn(run func(ctx context.Context) ([]QueueSummary, error)) *MockSqsService_Queues_Call {
	_c.Call.Return(run)
	return _c
}

// ReceiveMessages provides a mock function for the type MockSqsService
func (_mock *MockSqsService) ReceiveMessages(ctx context.Context, input ReceiveMessagesInput) (ReceiveMessagesResult, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ReceiveMessages")
	}

	var r0 ReceiveMessagesResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ReceiveMessagesInput) (ReceiveMessagesResult, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ReceiveMessagesInput) ReceiveMessagesResult); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(ReceiveMessagesResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ReceiveMessagesInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSqsService_ReceiveMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReceiveMessages'
type MockSqsService_ReceiveMessages_Call struct {
	*mock.Call
}

// ReceiveMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - input ReceiveMessagesInput
func (_e *MockSqsService_Expecter) ReceiveMessages(ctx interface{}, input interface{}) *MockSqsService_ReceiveMessages_Call {
	return &MockSqsService_ReceiveMessages_Call{Call: _e.mock.On("ReceiveMessages", ctx, input)}
}

func (_c *MockSqsService_ReceiveMessages_Call) Run(run func(ctx context.Context, input ReceiveMessagesInput)) *MockSqsService_ReceiveMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ReceiveMessagesInput
		if args[1] != nil {
			arg1 = args[1].(ReceiveMessagesInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSqsService_ReceiveMessages_Call) Return(receiveMessagesResult ReceiveMessagesResult, err error) *MockSqsService_ReceiveMessages_Call {
	_c.Call.Return(receiveMessagesResult, err)
	return _c
}

func (_c *MockSqsService_ReceiveMessages_Call) RunAndReturn(run func(ctx context.Context, input ReceiveMessagesInput) (ReceiveMessagesResult, error)) *MockSqsService_ReceiveMessages_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type MockSqsService
func (_mock *MockSqsService) SendMessage(ctx context.Context, input SendMessageInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, SendMessageInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSqsService_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockSqsService_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - input SendMessageInput
func (_e *MockSqsService_Expecter) SendMessage(ctx interface{}, input interface{}) *MockSqsService_SendMessage_Call {
	return &MockSqsService_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, input)}
}

func (_c *MockSqsService_SendMessage_Call) Run(run func(ctx context.Context, input SendMessageInput)) *MockSqsService_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 SendMessageInput
		if args[1] != nil {
			arg1 = args[1].(SendMessageInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSqsService_SendMessage_Call) Return(err error) *MockSqsService_SendMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSqsService_SendMessage_Call) RunAndReturn(run func(ctx context.Context, input SendMessageInput) error) *MockSqsService_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}
